#Config server recommended port number 8888
server:
  port: 8888
spring:
  application:
    name: DPM_ConfigServer
  cloud:
    config:
      server:
        bootstrap: false
        git:
          clone-on-start: true
          skip-ssl-validation: true
          uri: https://gitlab.com/naresh-i-technology/dpm_confingserver.git

#Link config server with gitlab account